// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUSFClMOi_YA4o1_7Kfv9OmybF2CnHn1k',
    appId: '1:810882140006:web:2c0d2ebf1e839c01da2aa7',
    messagingSenderId: '810882140006',
    projectId: 'cripto-din',
    authDomain: 'cripto-din.firebaseapp.com',
    storageBucket: 'cripto-din.firebasestorage.app',
    measurementId: 'G-F0CGJMLPS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASEt606JokLbysWPCbbqleN7coENIoObY',
    appId: '1:810882140006:android:6a49d94e244877d2da2aa7',
    messagingSenderId: '810882140006',
    projectId: 'cripto-din',
    storageBucket: 'cripto-din.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_gd03-d8MQLYXrIk7Ns2USAIDp9w8fSI',
    appId: '1:810882140006:ios:056de5dd4dd52ae2da2aa7',
    messagingSenderId: '810882140006',
    projectId: 'cripto-din',
    storageBucket: 'cripto-din.firebasestorage.app',
    iosBundleId: 'com.example.criptoDin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_gd03-d8MQLYXrIk7Ns2USAIDp9w8fSI',
    appId: '1:810882140006:ios:056de5dd4dd52ae2da2aa7',
    messagingSenderId: '810882140006',
    projectId: 'cripto-din',
    storageBucket: 'cripto-din.firebasestorage.app',
    iosBundleId: 'com.example.criptoDin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUSFClMOi_YA4o1_7Kfv9OmybF2CnHn1k',
    appId: '1:810882140006:web:62703305ddd4abddda2aa7',
    messagingSenderId: '810882140006',
    projectId: 'cripto-din',
    authDomain: 'cripto-din.firebaseapp.com',
    storageBucket: 'cripto-din.firebasestorage.app',
    measurementId: 'G-R82V11J7XM',
  );

}